### ISSUE TITLE
Insertion sort

### ISSUE THREAD

**Issue by yellowberard** [SuriyaaVijay/HacktoberFest2023#129]
I want to add algorithm for insertion sort.

**Comment by Harsha19-08** [comment]
i know the sorting techniques can u 
Please consider and assign this under Hacktoberfest_23 , As I am interested to contribute my self : )

**Comment by SonjeVilas** [comment]
hey could you please assign me this task I want to contribute

**Comment by Pradyumn04** [comment]
Assign me this issue with hacktober fest tag

**Comment by MazeJack** [comment]
Please assign me

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.
