### ISSUE TITLE
Number System Convertor

### ISSUE THREAD

**Issue by yellowberard** [SuriyaaVijay/HacktoberFest2023#131]
I want to add a project in the web development folder. 
In this project we can input decimal number and we will get the number in  different number system.

**Comment by 457ayan** [comment]
please assign this repo for me

**Comment by Saurabhchaudhary9799** [comment]
i want to work on this issue ,please assign this issue to me .

**Comment by rajanarahul93** [comment]
i want to work on this issue ,please assign this issue to me

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.
