### ISSUE TITLE
Data Analytics Project

### ISSUE THREAD

**Issue by KhushbooGupta2111** [SuriyaaVijay/HacktoberFest2023#182]
Want to add good Data & Analytics projects

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by pritthakkar** [comment]
I want to contribute to this, I have worked with many EDA projects it would be great if you assign this to me with the hactoberfest label.

**Comment by Kirti-Pant** [comment]
@KhushbooGupta2111 , I'm very much interested to work on this issue please assign me this issue

**Comment by Kirti-Pant** [comment]
can you also add it in hacktoberfest2023??

**Comment by KhushbooGupta2111** [comment]
I can't assign. The owner can.
