### ISSUE TITLE
Kmeans algorithm in Python

### ISSUE THREAD

**Issue by Amad-Ahmed** [SuriyaaVijay/HacktoberFest2023#232]
Kindly add kmeans algorithm which is used for clustering in python.

**Comment by Amad-Ahmed** [comment]
kindly assign this issue to me.

**Comment by shakti2002** [comment]
I want to work on this issue kindly assign this to me

**Comment by Amad-Ahmed** [comment]
I have already solved the issue and code has been merged, I believe.
