### ISSUE TITLE
Complete Wikipedia 

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [SuriyaaVijay/HacktoberFest2023#34]
Wikipedia , user can search any thing and he can get response based on his search 

example : 

![image](https://github.com/SuriyaaVijay/HacktoberFest2023/assets/127650446/8ba8cf3d-916c-4e10-8b60-6502a9c4f574)

Please consider and assign this under Hacktoberfest_23 , As I am interested to contribute my self : )

**Comment by SuriyaaVijay** [comment]
star the repository first

**Comment by Bharath-KumarReddy** [comment]
yes sure : )

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by vedali29** [comment]
i would like to contribute. kindly assign me to this please.

**Comment by Bharath-KumarReddy** [comment]
Can you please change the repo in such a way that it should obey the rules of hacktoberfest_23

As, This PR is excluded due to this repo is not obeying the rules of hacktoberfest : )

**Comment by Bharath-KumarReddy** [comment]
Hi.
Can you change the repo rules so that it will obey the rules of hacktoberfest_23 , My PR is excluded due to this repo is not obeying the laws or rules of hacktoberfest_23
