### ISSUE TITLE
Zigzag Conversion

### ISSUE THREAD

**Issue by talha-ansarii** [SuriyaaVijay/HacktoberFest2023#37]
The string "PAYPALISHIRING" is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility)

P   A   H   N
A P L S I I G
Y   I   R
And then read line by line: "PAHNAPLSIIGYIR"

Write the code that will take a string and make this conversion given a number of rows:

string convert(string s, int numRows);
 

Example 1:

Input: s = "PAYPALISHIRING", numRows = 3
Output: "PAHNAPLSIIGYIR"
Example 2:

Input: s = "PAYPALISHIRING", numRows = 4
Output: "PINALSIGYAHRPI"
Explanation:
P     I    N
A   L S  I G
Y A   H R
P     I
Example 3:

Input: s = "A", numRows = 1
Output: "A"
 

Constraints:

1 <= s.length <= 1000
s consists of English letters (lower-case and upper-case), ',' and '.'.
1 <= numRows <= 1000

I want to solve this problem under hacktoberfest
@SuriyaaVijay please assign me this issue

**Comment by talha-ansarii** [comment]
Starred and forked they repo already

**Comment by SuriyaaVijay** [comment]
assigned

**Comment by ghostbadfame** [comment]
I am interested can you please assign me this issue for hacktoberfest 2023

**Comment by Shikhar2702** [comment]
@SuriyaaVijay please assign me this issue

**Comment by ritik-sri** [comment]
@SuriyaaVijay please assign me this issue

**Comment by Gyanshu-Kumar** [comment]
Hi Can You Assign This issue to me

**Comment by ADNAAN18** [comment]
Please assign this issue to me. I can provide the solution with given constraints in detail at every step.

**Comment by panditakshay402** [comment]
hii @SuriyaaVijay @ghostbadfame @ADNAAN18 @ritik-sri @Gyanshu-Kumar , kindly assign this issue to me.

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by SuriyaaVijay** [comment]
assigned

**Comment by garvit0908** [comment]
hello , Can you please assign this issue to me...I will try to code it in a better way

**Comment by ADNAAN18** [comment]
@SuriyaaVijay could you please accept my pull request?

**Comment by ADNAAN18** [comment]
@SuriyaaVijay could you please accept my pull request it's been a long time since I posted the solution for the issue provided and this would be my first PR.
