### ISSUE TITLE
Pattern problem

### ISSUE THREAD

**Issue by talha-ansarii** [SuriyaaVijay/HacktoberFest2023#39]
I want to solve this pattern problem

                          1 
                    2 1   1 2 
                3 2 1       1 2 3 
            4 3 2 1           1 2 3 4 
                3 2 1       1 2 3 
                    2 1   1 2 
                        1
@SuriyaaVijay  Please assign this issue under hacktober fest

**Comment by SuriyaaVijay** [comment]
Star the repository first !

**Comment by Saurabhchaudhary9799** [comment]
i want to work on this issue ,please assign this issue to me .

**Comment by Pradyumn04** [comment]
Please assign me the issue with hacktober fest tag

**Comment by MazeJack** [comment]
Hello Sir, Can you assign to me this issue?

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by SuriyaaVijay** [comment]
assigned

**Comment by Ridham32** [comment]
@talha-ansarii Please assign this issue to me i know java , i can solve this
