### ISSUE TITLE
Printing a Matrix in spiral order in c++ 

### ISSUE THREAD

**Issue by SrijitaBaksi** [SuriyaaVijay/HacktoberFest2023#59]
I would like to contribute a code in c++ to write a matrix in spiral order as shown below
![matrix_in_spiral_form_1](https://github.com/SuriyaaVijay/HacktoberFest2023/assets/138782873/a62e4578-44b8-49a8-8628-9fdb6c3cb455)

**Comment by rkrajaryan02** [comment]
I would like to contribute a code in c++ to write a matrix in spiral order as shown below

**Comment by SuriyaaVijay** [comment]
Star the repository first !

**Comment by rkrajaryan02** [comment]
done

**Comment by ghostbadfame** [comment]
I am interested can you please assign me this issue for hacktoberfest 2023. I will write brute, optimal and best solution

**Comment by Yash9276** [comment]
<h1>Spiral Order</h1>
<p>code is written with understandable and user-friendly comments,
please assign this issue to me :)
</p>

**Comment by kartik2433** [comment]
Dear Repository Maintainer, I'm excited to participate in Hacktoberfest and contribute to your project. May I kindly request assignment to the 'Printing a Matrix in spiral order in C++' issue? I'm eager to make a meaningful open-source contribution. Thank you!

**Comment by 457ayan** [comment]
hey i am intrested please assign for this repo

**Comment by Ammu003** [comment]
i am interested in this please assign this to me @SuriyaaVijay

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by SuriyaaVijay** [comment]
ok

**Comment by Ammu003** [comment]
#283 this is my pr plz check it @SuriyaaVijay

**Comment by Ammu003** [comment]
@SuriyaaVijay this repo is excluded from hacktoberfest . can you do something about it as it is showing it is excluded and willl not be counted

**Comment by Apoorva01011** [comment]
Please assign it to me
