### ISSUE TITLE
Leetcode 2734. lexicographically-smallest-string-after-substring-operation

### ISSUE THREAD

**Issue by Sreenija03** [SuriyaaVijay/HacktoberFest2023#62]
I would like to contribute to the solution to this problem in C++

**Comment by ghostbadfame** [comment]
I am interested can you please assign me this issue for hacktoberfest 2023
I will provide brute optimal and best solution for this code

**Comment by Sreenija03** [comment]
@SuriyaaVijay Can you assign this issue under HacktoberFest 2023
