### ISSUE TITLE
Analog watch using react and js

### ISSUE THREAD

**Issue by sdhanraj300** [SuriyaaVijay/HacktoberFest2023#7]
Assign this issue to me.

**Comment by sahil5910** [comment]
Hey, I am well versed in multiple coding languages i would like to contribute to this issue, can you assign this to me

**Comment by SuriyaaVijay** [comment]
Assigned

**Comment by Saurabhchaudhary9799** [comment]
hey @SuriyaaVijay , please assign this to me

**Comment by harshitadubey1203** [comment]
Can I start with this @SuriyaaVijay

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.
