### ISSUE TITLE
Permutation using Quick Sort using C

### ISSUE THREAD

**Issue by iianuragii** [SuriyaaVijay/HacktoberFest2023#79]
# Can I add a code for doing Permutation using Quick Sort?

**Comment by vaibhav-rm** [comment]
I would like to be assigned this issue.

**Comment by Harsha19-08** [comment]
Please consider and assign this under Hacktoberfest_23 , As I am interested to contribute my self : ) an assign me this

**Comment by SonjeVilas** [comment]
hey could you please assign me this task I want to contribute

**Comment by Pradyumn04** [comment]
Assign me this issue with hacktober fest tag

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.
