### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by Yash9276** [SuriyaaVijay/HacktoberFest2023#80]
<h1>Blockchain</h1>
<p>I am a blockchain developer, I want to add a contracts folder in which I will add many contracts such as voting contracts, NFT contracts, ERC20 token contracts, and many more. So please send this issue to me
</p>

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by SuriyaaVijay** [comment]
doone
